### ISSUE TITLE
How to install into a private server

### ISSUE THREAD

**Issue by coolintan** [Kaltharos/RPGMods#1]
server folder is **VRisingDedicatedServer**

**Comment by Kaltharos** [comment]
it's like installing mod for the client side of the game, but instead of putting it inside the client folder, you put it in the server folder instead.

I recommend you join the Discord Server for the modding community, which would be https://discord.gg/XY5bNtNm4w
there you can learn more about modding.

**Comment by Kickbut101** [comment]
Is it possible to have this added in the readme or info?

If it's client side using a mod manager is easy. But theres obviously some slight guesswork if you are doing it to a private server
