### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Hellfoxblue** [Kaltharos/RPGMods#5]
https://github.com/Kaltharos/RPGMods/blob/59be30292a65dad94e72a892d24b0b2cf255f7e5/Commands/Mastery.cs#L53

misspelled Scythe as schyte.

https://github.com/Kaltharos/RPGMods/blob/59be30292a65dad94e72a892d24b0b2cf255f7e5/Commands/Mastery.cs#L56
https://github.com/Kaltharos/RPGMods/blob/59be30292a65dad94e72a892d24b0b2cf255f7e5/Commands/Mastery.cs#L105
The command uses Axes but the print out of mastery level says Axe not sure if intentional or not.
https://github.com/Kaltharos/RPGMods/blob/59be30292a65dad94e72a892d24b0b2cf255f7e5/Commands/Mastery.cs#L52
https://github.com/Kaltharos/RPGMods/blob/59be30292a65dad94e72a892d24b0b2cf255f7e5/Commands/Mastery.cs#L107
Same with slashers.
also fist and spell are both set to none not sure if intentional
https://github.com/Kaltharos/RPGMods/blob/59be30292a65dad94e72a892d24b0b2cf255f7e5/Systems/WeaponMasterSystem.cs#L314-L320

**Comment by Kaltharos** [comment]
Hi thanks for posting the issue.
I did remove the "s" from the mastery stats view, since other weapon doesn't uses it, it feels weird to have slashers and axes with an S, but then again, might be just me not being a native english speaker...
I guess it does make sense to use an "s" though... since you're holding 2 axe and 2 slasher... huh...

The "scythe" is definitely a typo.

And fist are spell are set together, that's intentional since spell mastery progress only when no weapon is wielded.
